/**
 * semo incubator — 인큐베이터 세션 관리
 *
 * semo incubator create --service-id <uuid> --channel <name>  — 프로젝트 세션 생성
 * semo incubator list                                         — 활성 세션 목록
 * semo incubator stop --service-id <uuid>                     — 세션 중지 + 아카이브
 * semo incubator status --service-id <uuid>                   — 세션 상태 조회
 */

import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { getPool, closeConnection } from '../database';
import { ensureEnforcementHooks, ensureRulesSymlink } from '../semo-workspace';
import { semoHome, claudeHome } from '../paths.js';
const DB_SCHEMA = process.env.SEMICOLONY_DB_SCHEMA ?? process.env.SEMO_DB_SCHEMA ?? 'semo';

// ============================================================
// Paths (lazy — SEMO_HOME 런타임 변경 반영)
// ============================================================

function sessionsRoot(): string {
  return path.join(semoHome(), 'sessions');
}
function sharedHooks(): string {
  return path.join(semoHome(), 'shared', 'hooks');
}
function sharedSkills(): string {
  return path.join(claudeHome(), 'skills');
}
function semoEnv(): string {
  return path.join(claudeHome(), 'semo', '.env');
}

function requireDashboardUrl(): string {
  const url = process.env.SEMO_DASHBOARD_URL;
  if (!url) {
    console.error(
      chalk.red(
        'SEMO_DASHBOARD_URL 이 설정되지 않았습니다. semo incubator/sandbox 명령은 SEMO 대시보드와 통신합니다.\n' +
          '예: export SEMO_DASHBOARD_URL=https://my-semo.example.com',
      ),
    );
    process.exit(1);
  }
  return url;
}
function archiveRoot(): string {
  return path.join(semoHome(), 'archive');
}

// SEMO 인큐베이터는 SEMO 레포의 `.claude/agents/` 디렉토리를 세션에 심링크한다.
// SEMO_REPO_PATH 가 지정되어 있으면 그 경로를, 아니면 `~/.claude/agents` 를 사용.
const SHARED_AGENTS = process.env.SEMO_REPO_PATH
  ? path.join(process.env.SEMO_REPO_PATH, '.claude', 'agents')
  : path.join(claudeHome(), 'agents');
const LAUNCHD_DIR = path.join(os.homedir(), 'Library', 'LaunchAgents');

// ============================================================
// Session Directory Scaffold
// ============================================================

interface CreateOptions {
  serviceId: string;
  channel?: string;
  serviceName?: string;
}

function ensureSessionDir(serviceId: string): string {
  const sessionDir = path.join(sessionsRoot(), serviceId);
  const dirs = [sessionDir, path.join(sessionDir, '.claude'), path.join(sessionDir, 'memory')];
  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return sessionDir;
}

function createSymlinks(sessionDir: string): void {
  const links: Array<[string, string]> = [
    [SHARED_AGENTS, path.join(sessionDir, '.claude', 'agents')],
    [sharedSkills(), path.join(sessionDir, '.claude', 'skills')],
  ];

  for (const [target, linkPath] of links) {
    if (fs.existsSync(linkPath)) {
      const stat = fs.lstatSync(linkPath);
      if (stat.isSymbolicLink()) fs.unlinkSync(linkPath);
      else continue; // 실제 디렉토리면 건드리지 않음
    }
    if (fs.existsSync(target)) {
      fs.symlinkSync(target, linkPath, 'dir');
    }
  }
}

function writeClaudeMd(
  sessionDir: string,
  serviceId: string,
  serviceName: string,
  channel?: string,
): void {
  const content = `# Incubator Session — ${serviceName}

> Auto-generated by \`semo incubator create\`
> Service ID: ${serviceId}
> Channel: ${channel || '(미할당)'}
> Created: ${new Date().toISOString().slice(0, 10)}

## Context

이 세션은 인큐베이터 프로젝트 **${serviceName}**의 전용 Claude Code 세션이다.

### 라우팅 규칙

유저 메시지를 받으면 아래 우선순위로 봇 Agent를 선택:

1. **명시적 봇 지정**: "디자인팀에게 물어봐" → Agent(designclaw)
2. **현재 Phase 기반**: Dashboard API에서 current_phase 조회 → Phase별 담당 봇 매핑
3. **키워드 분기**: 인프라/배포 → infraclaw, 리뷰/PR → reviewclaw, 마케팅/SEO → growthclaw
4. **폴백**: Agent(semiclaw) — PM/오케스트레이터

Phase → 봇 매핑은 Dashboard API \`GET /api/projects/{service_id}\`의 current_phase에 따름.
봇 프로필은 KB에서 동적 로드됨 (\`semo kb get {botId} slack-config\`).

### 응답 포맷

reply() 호출 시 반드시 \`bot_id\` 파라미터를 전달하여 봇 정체성을 표시.
예: \`reply(text="분석 결과입니다...", bot_id="planclaw", ...)\`
응답 텍스트에 [봇이름] 접두사를 붙이지 않는다 — bot_id가 Slack 표시를 자동 처리.

## KB 도메인

- 서비스 정보: \`semo kb get ${serviceName} base-information\`
- 프로젝트 현황: Dashboard API \`GET /api/gfp/{service_id}\`

## Shared Resources

- Agents: .claude/agents/ (심링크 → 공유)
- Skills: .claude/skills/ (심링크 → 공유)
- KB: semo kb CLI
`;

  fs.writeFileSync(path.join(sessionDir, 'CLAUDE.md'), content, 'utf-8');
}

// channel-slack 패키지 위치. SEMO_REPO_PATH 가 지정되면 그 경로의 packages/channel-slack,
// 아니면 npx 로 실행 (npm 배포 후 `@team-semicolon/channel-slack` 으로 호출 가능).
const CHANNEL_SLACK_DIR = process.env.SEMO_REPO_PATH
  ? path.join(process.env.SEMO_REPO_PATH, 'packages', 'channel-slack')
  : '';

function writeSettingsJson(sessionDir: string, serviceId?: string, channel?: string): void {
  const settings: Record<string, unknown> = {
    permissions: {
      allow: ['Bash(semo kb:*)', 'Bash(semo context:*)', 'Bash(curl:*)', 'Bash(node:*)'],
    },
    hooks: {
      SessionStart: [
        {
          matcher: '',
          hooks: [
            {
              type: 'command',
              command: `. ${semoEnv()} 2>/dev/null; semo context sync 2>/dev/null || true`,
              timeout: 30,
            },
            {
              type: 'command',
              command: `bash ${sharedHooks()}/cron-reregister.sh`,
              timeout: 5000,
            },
          ],
        },
      ],
      Stop: [
        {
          matcher: '',
          hooks: [
            {
              type: 'command',
              command: `. ${semoEnv()} 2>/dev/null; semo context push 2>/dev/null || true`,
              timeout: 30,
            },
          ],
        },
      ],
    },
  };

  fs.writeFileSync(
    path.join(sessionDir, '.claude', 'settings.json'),
    JSON.stringify(settings, null, 2),
    'utf-8',
  );

  // .mcp.json — Channel Slack 플러그인 등록
  // SEMO_REPO_PATH 가 지정되면 source tsx 로 실행, 아니면 npx 로 published 패키지 실행.
  const channelSlackArgs = CHANNEL_SLACK_DIR
    ? ['tsx', path.join(CHANNEL_SLACK_DIR, 'src', 'index.ts')]
    : ['@team-semicolon/channel-slack'];
  const mcpConfig: Record<string, unknown> = {
    mcpServers: {
      'semo-channel-slack': {
        command: 'npx',
        args: channelSlackArgs,
        env: {
          SLACK_CHANNEL_ID: channel || '',
          SEMO_SERVICE_ID: serviceId || '',
        },
      },
    },
  };

  fs.writeFileSync(path.join(sessionDir, '.mcp.json'), JSON.stringify(mcpConfig, null, 2), 'utf-8');
}

function writeMemoryFiles(sessionDir: string, serviceName: string): void {
  fs.writeFileSync(
    path.join(sessionDir, 'memory', 'MEMORY.md'),
    `# ${serviceName} — Incubator Session Memory\n\n(초기 상태)\n`,
    'utf-8',
  );

  fs.writeFileSync(
    path.join(sessionDir, 'memory', 'context.md'),
    `# Session Context\n\n- Phase: 0 (온보딩)\n- Track A: 대기\n- Track B: 미시작\n`,
    'utf-8',
  );
}

// ============================================================
// launchd plist
// ============================================================

function getLaunchdLabel(serviceId: string): string {
  return `com.semo.incubator.${serviceId.slice(0, 8)}`;
}

function writeLaunchdPlist(serviceId: string, sessionDir: string): string {
  fs.mkdirSync(LAUNCHD_DIR, { recursive: true });

  const label = getLaunchdLabel(serviceId);
  const plistPath = path.join(LAUNCHD_DIR, `${label}.plist`);
  const logDir = path.join(sessionDir, 'logs');
  fs.mkdirSync(logDir, { recursive: true });

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/claude</string>
    <string>--resume</string>
    <string>--dangerously-skip-permissions</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${sessionDir}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${os.homedir()}</string>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
  </dict>
  <key>RunAtLoad</key>
  <false/>
  <key>KeepAlive</key>
  <false/>
  <key>StandardOutPath</key>
  <string>${logDir}/stdout.log</string>
  <key>StandardErrorPath</key>
  <string>${logDir}/stderr.log</string>
</dict>
</plist>`;

  fs.writeFileSync(plistPath, plist, 'utf-8');
  return plistPath;
}

// ============================================================
// DB 연동
// ============================================================

interface SessionRecord {
  service_id: string;
  service_name: string;
  channel: string | null;
  session_dir: string;
  status: 'active' | 'stopped' | 'archived';
  created_at: string;
}

async function upsertSessionRecord(
  serviceId: string,
  serviceName: string,
  channel: string | null,
  sessionDir: string,
): Promise<void> {
  const pool = getPool();
  await pool.query(
    `INSERT INTO ${DB_SCHEMA}.incubator_sessions
       (service_id, service_name, channel, session_dir, status)
     VALUES ($1, $2, $3, $4, 'active')
     ON CONFLICT (service_id) DO UPDATE SET
       status = 'active',
       session_dir = $4,
       channel = COALESCE($3, ${DB_SCHEMA}.incubator_sessions.channel)`,
    [serviceId, serviceName, channel, sessionDir],
  );
}

async function updateSessionStatus(
  serviceId: string,
  status: 'active' | 'stopped' | 'archived',
): Promise<void> {
  const pool = getPool();
  await pool.query(`UPDATE ${DB_SCHEMA}.incubator_sessions SET status = $2 WHERE service_id = $1`, [
    serviceId,
    status,
  ]);
}

async function listSessions(): Promise<SessionRecord[]> {
  const pool = getPool();
  const result = await pool.query<SessionRecord>(
    `SELECT service_id, service_name, channel, session_dir, status,
            created_at::text
     FROM ${DB_SCHEMA}.incubator_sessions
     ORDER BY created_at DESC`,
  );
  return result.rows;
}

async function getSession(serviceId: string): Promise<SessionRecord | null> {
  const pool = getPool();
  const result = await pool.query<SessionRecord>(
    `SELECT service_id, service_name, channel, session_dir, status,
            created_at::text
     FROM ${DB_SCHEMA}.incubator_sessions
     WHERE service_id = $1`,
    [serviceId],
  );
  return result.rows[0] || null;
}

// ============================================================
// Command Registration
// ============================================================

export function registerIncubatorCommands(program: Command): void {
  const incubator = program
    .command('incubator')
    .description('인큐베이터 세션 관리 — 생성, 목록, 중지');

  // ── semo incubator create ──
  incubator
    .command('create')
    .description('인큐베이터 프로젝트용 Claude Code 세션 생성')
    .requiredOption('--service-id <uuid>', '서비스 UUID')
    .option('--channel <name>', 'Slack 채널명 (예: #incubator-요리왕)')
    .option('--name <name>', '서비스명 (미지정 시 DB에서 조회)')
    .action(async (options: { serviceId: string; channel?: string; name?: string }) => {
      const spinner = ora('인큐베이터 세션 생성 중...').start();

      try {
        // 1. 서비스명 확인
        let serviceName = options.name || options.serviceId.slice(0, 8);
        if (!options.name) {
          try {
            const { kbGet } = await import('../kb.js');
            const pool = getPool();
            // KB pipeline/config에서 project_name 조회
            const entry = await kbGet(pool, options.serviceId, 'pipeline', 'config');
            if (entry?.metadata?.project_name) {
              serviceName = entry.metadata.project_name as string;
            } else {
              // fallback: base-information에서 이름 추출
              const baseEntry = await kbGet(pool, options.serviceId, 'base-information');
              if (baseEntry?.content) {
                const nameMatch = baseEntry.content.match(/^#\s*(.+)/m);
                if (nameMatch) serviceName = nameMatch[1].trim();
              }
            }
          } catch {
            // DB 접속 실패 시 UUID 앞 8자리 사용
          }
        }

        // 2. 세션 디렉토리 생성
        spinner.text = '디렉토리 구조 생성...';
        const sessionDir = ensureSessionDir(options.serviceId);

        // 3. 심링크 설정
        spinner.text = '공유 리소스 심링크...';
        createSymlinks(sessionDir);

        // 4. CLAUDE.md 생성
        spinner.text = 'CLAUDE.md 생성...';
        writeClaudeMd(sessionDir, options.serviceId, serviceName, options.channel);

        // 5. settings.json 생성
        writeSettingsJson(sessionDir, options.serviceId, options.channel);

        // 5-b. enforcement 훅 + rules 심링크
        ensureEnforcementHooks(sessionDir);
        ensureRulesSymlink(sessionDir);

        // 6. memory 파일 생성
        writeMemoryFiles(sessionDir, serviceName);

        // 7. launchd plist 생성
        spinner.text = 'launchd plist 생성...';
        const plistPath = writeLaunchdPlist(options.serviceId, sessionDir);

        // 8. DB 기록
        spinner.text = 'DB 기록...';
        try {
          await upsertSessionRecord(
            options.serviceId,
            serviceName,
            options.channel || null,
            sessionDir,
          );
        } catch {
          // DB 없어도 로컬 세션은 생성
        }

        spinner.succeed(`인큐베이터 세션 생성 완료: ${serviceName}`);
        console.log();
        console.log(chalk.gray('  세션 디렉토리:'), sessionDir);
        console.log(chalk.gray('  launchd plist:'), plistPath);
        console.log(chalk.gray('  채널:'), options.channel || '(미할당)');
        console.log();
        console.log(chalk.cyan('세션 시작:'), `cd ${sessionDir} && claude`);
        console.log(chalk.cyan('서비스로 시작:'), `launchctl load ${plistPath}`);
      } catch (err) {
        spinner.fail(`세션 생성 실패: ${err instanceof Error ? err.message : err}`);
      } finally {
        await closeConnection();
      }
    });

  // ── semo incubator list ──
  incubator
    .command('list')
    .description('활성 인큐베이터 세션 목록')
    .option('--all', '중지/아카이브 포함')
    .action(async (options: { all?: boolean }) => {
      const spinner = ora('세션 목록 조회 중...').start();

      try {
        // DB 조회 시도
        let sessions: SessionRecord[] = [];
        try {
          sessions = await listSessions();
        } catch {
          // DB 실패 시 로컬 디렉토리 스캔
          spinner.text = '로컬 디렉토리 스캔...';
          const root = sessionsRoot();
          if (fs.existsSync(root)) {
            const dirs = fs.readdirSync(root);
            sessions = dirs
              .filter((d) => fs.existsSync(path.join(root, d, 'CLAUDE.md')))
              .map((d) => ({
                service_id: d,
                service_name: d.slice(0, 8),
                channel: null,
                session_dir: path.join(root, d),
                status: 'active' as const,
                created_at: '',
              }));
          }
        }

        if (!options.all) {
          sessions = sessions.filter((s) => s.status === 'active');
        }

        spinner.stop();

        if (sessions.length === 0) {
          console.log(chalk.yellow('활성 인큐베이터 세션이 없습니다.'));
          return;
        }

        console.log(chalk.bold(`인큐베이터 세션 (${sessions.length}개)\n`));

        for (const s of sessions) {
          const statusIcon =
            s.status === 'active'
              ? chalk.green('●')
              : s.status === 'stopped'
                ? chalk.yellow('○')
                : chalk.gray('◌');
          console.log(
            `  ${statusIcon} ${chalk.bold(s.service_name)} ${chalk.gray(`(${s.service_id.slice(0, 8)})`)}`,
          );
          if (s.channel) console.log(`    채널: ${s.channel}`);
          if (s.created_at) console.log(`    생성: ${s.created_at.slice(0, 10)}`);
          console.log(`    경로: ${s.session_dir}`);
          console.log();
        }
      } catch (err) {
        spinner.fail(`목록 조회 실패: ${err instanceof Error ? err.message : err}`);
      } finally {
        await closeConnection();
      }
    });

  // ── semo incubator stop ──
  incubator
    .command('stop')
    .description('인큐베이터 세션 중지')
    .requiredOption('--service-id <uuid>', '서비스 UUID')
    .option('--archive', '세션 디렉토리 아카이브')
    .action(async (options: { serviceId: string; archive?: boolean }) => {
      const spinner = ora('세션 중지 중...').start();

      try {
        const sessionDir = path.join(sessionsRoot(), options.serviceId);
        const label = getLaunchdLabel(options.serviceId);
        const plistPath = path.join(LAUNCHD_DIR, `${label}.plist`);

        // 1. launchd 언로드
        if (fs.existsSync(plistPath)) {
          try {
            const { execSync } = await import('child_process');
            execSync(`launchctl unload ${plistPath} 2>/dev/null || true`);
            fs.unlinkSync(plistPath);
            spinner.text = 'launchd 서비스 중지...';
          } catch {
            // 이미 언로드된 경우 무시
          }
        }

        // 2. DB 상태 업데이트
        try {
          await updateSessionStatus(options.serviceId, options.archive ? 'archived' : 'stopped');
        } catch {
          // DB 없어도 계속
        }

        // 3. 아카이브
        if (options.archive && fs.existsSync(sessionDir)) {
          const archiveDir = archiveRoot();
          fs.mkdirSync(archiveDir, { recursive: true });
          const archivePath = path.join(archiveDir, options.serviceId);
          fs.renameSync(sessionDir, archivePath);
          spinner.succeed(`세션 아카이브 완료: ${archivePath}`);
        } else {
          spinner.succeed(`세션 중지 완료: ${options.serviceId.slice(0, 8)}`);
          if (fs.existsSync(sessionDir)) {
            console.log(chalk.gray(`  디렉토리 유지: ${sessionDir}`));
            console.log(
              chalk.gray(
                `  완전 삭제: semo incubator stop --service-id ${options.serviceId} --archive`,
              ),
            );
          }
        }
      } catch (err) {
        spinner.fail(`세션 중지 실패: ${err instanceof Error ? err.message : err}`);
      } finally {
        await closeConnection();
      }
    });

  // ── semo incubator status ──
  incubator
    .command('status')
    .description('인큐베이터 세션 상태 조회')
    .requiredOption('--service-id <uuid>', '서비스 UUID')
    .action(async (options: { serviceId: string }) => {
      try {
        const sessionDir = path.join(sessionsRoot(), options.serviceId);
        const label = getLaunchdLabel(options.serviceId);
        const plistPath = path.join(LAUNCHD_DIR, `${label}.plist`);

        console.log(chalk.bold(`\n세션 상태: ${options.serviceId.slice(0, 8)}\n`));

        // 디렉토리 존재 여부
        const dirExists = fs.existsSync(sessionDir);
        console.log(
          `  디렉토리: ${dirExists ? chalk.green('존재') : chalk.red('없음')} ${chalk.gray(sessionDir)}`,
        );

        // CLAUDE.md 존재 여부
        if (dirExists) {
          const claudeMd = fs.existsSync(path.join(sessionDir, 'CLAUDE.md'));
          console.log(`  CLAUDE.md: ${claudeMd ? chalk.green('있음') : chalk.red('없음')}`);

          // 심링크 상태
          const agentsLink = path.join(sessionDir, '.claude', 'agents');
          const skillsLink = path.join(sessionDir, '.claude', 'skills');
          const agentsOk = fs.existsSync(agentsLink) && fs.lstatSync(agentsLink).isSymbolicLink();
          const skillsOk = fs.existsSync(skillsLink) && fs.lstatSync(skillsLink).isSymbolicLink();
          console.log(
            `  심링크: agents=${agentsOk ? chalk.green('OK') : chalk.red('X')} skills=${skillsOk ? chalk.green('OK') : chalk.red('X')}`,
          );
        }

        // launchd 상태
        const plistExists = fs.existsSync(plistPath);
        console.log(`  launchd: ${plistExists ? chalk.green('등록') : chalk.gray('미등록')}`);

        // DB 상태
        try {
          const session = await getSession(options.serviceId);
          if (session) {
            console.log(`  DB 상태: ${chalk.cyan(session.status)}`);
            console.log(`  생성일: ${session.created_at?.slice(0, 10) || '?'}`);
            if (session.channel) console.log(`  채널: ${session.channel}`);
          } else {
            console.log(`  DB 상태: ${chalk.gray('미등록')}`);
          }
        } catch {
          console.log(`  DB 상태: ${chalk.gray('(DB 연결 불가)')}`);
        }

        console.log();
      } finally {
        await closeConnection();
      }
    });

  // ============================================================
  // semo incubator start — CP-1 신규/기존 프로젝트 온보딩
  //   • 도메인 충돌 검사 → 신규면 ontology + KB pipeline/config 등록
  //   • 대시보드 callback 으로 incubator-checkpoint=1 등록
  //   • 결과: service_id, dashboard URL, 다음 CP 안내
  // ============================================================

  incubator
    .command('start')
    .description('CP-1 온보딩 — 신규 프로젝트 등록 또는 기존 프로젝트 resume')
    .requiredOption('--domain <domain>', '서비스 도메인 (예: coffeehub)')
    .requiredOption('--po <po>', 'PO (담당자 닉네임 또는 도메인)')
    .requiredOption('--desc <desc>', '한 줄 설명')
    .option('--name <name>', '프로젝트 이름 (미지정 시 도메인을 사용)')
    .option('--target-launch <date>', '목표 런칭 시점 (YYYY-MM-DD)')
    .option('--preset <preset>', '인큐베이터 프리셋 (sequential | parallel)', 'sequential')
    .option('--json', '결과를 JSON 으로 출력 (봇 파싱용)')
    .action(
      async (options: {
        domain: string;
        po: string;
        desc: string;
        name?: string;
        targetLaunch?: string;
        preset: string;
        json?: boolean;
      }) => {
        const dashboardUrl = requireDashboardUrl();
        const pool = getPool();
        const { ontoRegister, generateEmbedding } = await import('../kb.js');

        const out: Record<string, unknown> = { domain: options.domain };
        const log = (msg: string) => {
          if (!options.json) console.log(msg);
        };

        try {
          // 1. 기존 등록 확인 (raw SQL — pipeline/config 는 schema 상 singleton 으로 등록되어 있어
          //    kbGet/kbUpsert 의 splitKey 검증을 피한다. service-migrate.ts 와 동일 패턴.)
          const existingRes = await pool.query(
            `SELECT content, metadata FROM ${DB_SCHEMA}.knowledge_base
             WHERE domain = $1 AND key = 'pipeline' AND sub_key = 'config'`,
            [options.domain],
          );
          if (existingRes.rowCount && existingRes.rowCount > 0) {
            const m = (existingRes.rows[0].metadata ?? {}) as Record<string, unknown>;
            out.status = 'exists';
            out.service_id = m.service_id ?? options.domain;
            out.current_phase = m.current_phase ?? 0;
            out.dashboard_url = `${dashboardUrl}/projects/${m.service_id ?? options.domain}`;
            log(chalk.yellow(`이미 등록된 프로젝트: ${options.domain}`));
            log(chalk.gray(`  service_id: ${out.service_id}`));
            log(chalk.gray(`  current_phase: ${out.current_phase}`));
            log(chalk.gray(`  대시보드: ${out.dashboard_url}`));
            log(
              chalk.cyan('  → resume 가 필요하면 semo incubator resume --domain ' + options.domain),
            );
            if (options.json) console.log(JSON.stringify(out, null, 2));
            return;
          }

          // 2. ontology 등록 (없으면 service 타입으로)
          const ontoRes = await ontoRegister(pool, {
            domain: options.domain,
            entity_type: 'service',
            description: options.desc,
            tags: ['incubator', 'cp1'],
          });
          if (!ontoRes.success && !/이미 등록/.test(ontoRes.error || '')) {
            console.error(chalk.red(`ontology 등록 실패: ${ontoRes.error}`));
            process.exit(1);
          }

          // 3. service_id 발급 + KB pipeline/config upsert (raw SQL)
          const serviceId = (
            globalThis.crypto?.randomUUID
              ? globalThis.crypto.randomUUID()
              : `${Date.now().toString(16)}-${Math.random().toString(16).slice(2, 10)}`
          ) as string;
          const projectName = options.name || options.domain;
          const metadata: Record<string, unknown> = {
            service_id: serviceId,
            project_name: projectName,
            owner_name: options.po,
            status: 'discovery',
            lifecycle: 'build',
            current_phase: 0,
            preset: options.preset,
            service_type: 'incubator',
            created_at: new Date().toISOString(),
          };
          if (options.targetLaunch) metadata.target_launch_date = options.targetLaunch;

          // exists early-return 으로 충돌 시점이 거의 없지만, race condition 안전망으로 ON CONFLICT
          // 유지. 이 시점엔 항상 신규 row 이므로 metadata 는 단순 교체.
          const embeddingText = `${projectName}: ${options.desc}`;
          const embedding = await generateEmbedding(embeddingText);
          const embeddingStr = embedding ? `[${embedding.join(',')}]` : null;
          try {
            await pool.query(
              `INSERT INTO ${DB_SCHEMA}.knowledge_base
                 (domain, key, sub_key, content, metadata, created_by, embedding)
               VALUES ($1, 'pipeline', 'config', $2, $3::jsonb, 'semo-incubator-cli', $4::vector)
               ON CONFLICT (domain, key, sub_key) DO UPDATE SET
                 content = EXCLUDED.content,
                 metadata = EXCLUDED.metadata,
                 embedding = EXCLUDED.embedding,
                 updated_at = NOW()`,
              [options.domain, options.desc, JSON.stringify(metadata), embeddingStr],
            );
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            console.error(chalk.red(`KB upsert 실패: ${msg}`));
            process.exit(1);
          }

          // 4. 대시보드 callback (best-effort)
          let callbackOk = false;
          try {
            const cb = await fetch(`${dashboardUrl}/api/projects/callback`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                type: 'incubator-checkpoint',
                service_id: serviceId,
                checkpoint: 1,
                status: 'in-progress',
                summary: `${projectName} 인큐베이팅 시작 (PO=${options.po})`,
                bot_id: 'semiclaw',
              }),
              signal: AbortSignal.timeout(10000),
            });
            callbackOk = cb.ok;
          } catch {
            callbackOk = false;
          }

          out.status = 'created';
          out.service_id = serviceId;
          out.project_name = projectName;
          out.dashboard_url = `${dashboardUrl}/projects/${serviceId}`;
          out.callback_ok = callbackOk;
          out.next_cp = 2;
          out.next_owner = 'planclaw';

          log(chalk.green(`✅ ${projectName} 인큐베이팅 시작 (CP-1 등록 완료)`));
          log(chalk.gray(`  service_id: ${serviceId}`));
          log(chalk.gray(`  도메인: ${options.domain}`));
          log(chalk.gray(`  PO: ${options.po}`));
          log(chalk.gray(`  대시보드 callback: ${callbackOk ? '성공' : '실패 (KB 등록만 반영)'}`));
          log(chalk.cyan(`  대시보드: ${out.dashboard_url}`));
          log(chalk.cyan(`  다음: CP-2 요구사항 디스커버리 → @planclaw`));
          if (options.json) console.log(JSON.stringify(out, null, 2));
        } finally {
          await closeConnection();
        }
      },
    );

  // ============================================================
  // Sandbox subcommands
  // ============================================================

  // Lazy: SEMO_DASHBOARD_URL 미설정 시 sandbox 명령 실행 시점에서만 에러.
  const sandboxBaseUrl = (): string => requireDashboardUrl();

  function sandboxHeaders(): Record<string, string> {
    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    const secret = process.env.SANDBOX_API_SECRET;
    if (secret) headers['x-sandbox-secret'] = secret;
    return headers;
  }

  const sandbox = incubator
    .command('sandbox')
    .description('인큐베이션 샌드박스 — 파이프라인 검증용 가상 프로젝트 관리');

  sandbox
    .command('create')
    .description('샌드박스 프로젝트 생성')
    .requiredOption(
      '--scenario <id>',
      '시나리오 ID (minicafe, creator-pulse, quickdrop, office-hub, petcare)',
    )
    .requiredOption('--depth <depth>', '검증 범위 (plan-only, full, e2e)')
    .option(
      '--po-mode <mode>',
      '가상 PO 모드 (auto-pilot, semi-auto, interactive, full-interaction)',
      'auto-pilot',
    )
    .option('--live', '실제 봇 실행 모드 (기본: mock)')
    .action(async (options) => {
      const spinner = ora('샌드박스 생성 중...').start();
      try {
        const res = await fetch(`${sandboxBaseUrl()}/api/projects/sandbox`, {
          method: 'POST',
          headers: sandboxHeaders(),
          body: JSON.stringify({
            scenario_id: options.scenario,
            depth: options.depth,
            virtual_po_mode: options.poMode,
            mode: options.live ? 'live' : 'mock',
          }),
          signal: AbortSignal.timeout(15000),
        });

        if (!res.ok) {
          const err = await res.json().catch(() => ({ error: 'Unknown error' }));
          spinner.fail(`생성 실패: ${err.error}`);
          return;
        }

        const project = await res.json();
        spinner.succeed('샌드박스 생성 완료');
        console.log();
        console.log(`  프로젝트: ${chalk.cyan(project.project_name)}`);
        console.log(`  ID: ${chalk.gray(project.service_id)}`);
        console.log(
          `  대시보드: ${chalk.underline(`${sandboxBaseUrl()}/gfp/${project.service_id}`)}`,
        );
        console.log(`  관리: ${chalk.underline(`${sandboxBaseUrl()}/projects/sandbox`)}`);
      } catch (err) {
        spinner.fail(`생성 실패: ${err instanceof Error ? err.message : err}`);
      }
    });

  sandbox
    .command('list')
    .description('활성 샌드박스 목록')
    .action(async () => {
      const spinner = ora('목록 조회 중...').start();
      try {
        const res = await fetch(`${sandboxBaseUrl()}/api/projects/sandbox`, {
          headers: sandboxHeaders(),
          signal: AbortSignal.timeout(10000),
        });

        if (!res.ok) {
          const err = await res.json().catch(() => ({ error: 'Unknown error' }));
          spinner.fail(`목록 조회 실패: ${err.error}`);
          return;
        }

        const projects = await res.json();
        spinner.stop();

        if (!Array.isArray(projects) || projects.length === 0) {
          console.log(chalk.gray('활성 샌드박스 없음'));
          return;
        }

        console.log(chalk.bold(`활성 샌드박스 ${projects.length}개\n`));
        for (const p of projects) {
          const sb = p.metadata?.sandbox;
          const stats = sb?.run_stats;
          const status = stats?.completed_at ? chalk.green('완료') : chalk.yellow('진행중');
          console.log(
            `  ${status} ${chalk.cyan(p.project_name)} — ${sb?.scenario_id || '?'} | Phase ${p.current_phase}/9 | ${sb?.virtual_po?.mode || '?'}`,
          );
          console.log(`       ${chalk.gray(p.service_id)}`);
        }
      } catch (err) {
        spinner.fail(`조회 실패: ${err instanceof Error ? err.message : err}`);
      }
    });

  sandbox
    .command('report')
    .description('샌드박스 런 리포트')
    .requiredOption('--service-id <uuid>', '서비스 UUID')
    .action(async (options) => {
      const spinner = ora('리포트 조회 중...').start();
      try {
        const res = await fetch(
          `${sandboxBaseUrl()}/api/projects/sandbox/report?service_id=${encodeURIComponent(options.serviceId)}`,
          { headers: sandboxHeaders(), signal: AbortSignal.timeout(10000) },
        );

        if (!res.ok) {
          const err = await res.json().catch(() => ({ error: 'Unknown error' }));
          spinner.fail(`리포트 조회 실패: ${err.error}`);
          return;
        }

        const report = await res.json();
        spinner.stop();

        const stats = report.run_stats;
        console.log(chalk.bold(`\n샌드박스 리포트: ${report.project.project_name}\n`));
        console.log(`  시나리오: ${report.config.scenario_id}`);
        console.log(`  모드: ${report.config.mode} | PO: ${report.config.virtual_po.mode}`);
        console.log(`  Phase 완료: ${stats?.phases_completed ?? 0}`);
        console.log(`  섹션 리뷰: ${stats?.sections_reviewed ?? 0}`);
        console.log(`  거절: ${stats?.rejections ?? 0}`);
        console.log(
          `  상태: ${stats?.completed_at ? chalk.green('완료') : chalk.yellow('진행중')}`,
        );

        const v = report.verification;
        if (v) {
          console.log(
            `\n  검증: ${v.passed ? chalk.green('PASS') : chalk.red(`FAIL (${v.issues.length}건)`)}`,
          );
          if (!v.passed) {
            for (const issue of v.issues) {
              console.log(`    - ${issue}`);
            }
          }
        }
      } catch (err) {
        spinner.fail(`조회 실패: ${err instanceof Error ? err.message : err}`);
      }
    });

  sandbox
    .command('teardown')
    .description('샌드박스 정리 (삭제)')
    .option('--service-id <uuid>', '특정 서비스 UUID')
    .option('--all', '모든 샌드박스 정리')
    .action(async (options) => {
      if (!options.serviceId && !options.all) {
        console.log(chalk.red('--service-id 또는 --all 필요'));
        return;
      }

      const spinner = ora('샌드박스 정리 중...').start();
      try {
        const qs = options.all ? 'all=true' : `service_id=${encodeURIComponent(options.serviceId)}`;
        const res = await fetch(`${sandboxBaseUrl()}/api/projects/sandbox?${qs}`, {
          method: 'DELETE',
          headers: sandboxHeaders(),
          signal: AbortSignal.timeout(15000),
        });

        if (!res.ok) {
          const err = await res.json().catch(() => ({ error: 'Unknown error' }));
          spinner.fail(`정리 실패: ${err.error}`);
          return;
        }

        const result = await res.json();
        spinner.succeed(result.message || '정리 완료');
      } catch (err) {
        spinner.fail(`정리 실패: ${err instanceof Error ? err.message : err}`);
      }
    });

  sandbox
    .command('reinit')
    .description('샌드박스 초기화 (같은 프로젝트 ID 유지, Phase 0부터 재시작)')
    .requiredOption('--service-id <uuid>', '서비스 UUID')
    .option('--scenario <id>', '시나리오 변경')
    .option(
      '--po-mode <mode>',
      'PO 모드 변경 (auto-pilot, semi-auto, interactive, full-interaction)',
    )
    .option('--rejection-rate <rate>', '거절률 변경 (0.0-1.0)', parseFloat)
    .action(async (options) => {
      const spinner = ora('샌드박스 초기화 중...').start();
      try {
        const body: Record<string, unknown> = {
          service_id: options.serviceId,
          action: 'reinitialize',
        };
        if (options.scenario) body.scenario_id = options.scenario;
        if (options.poMode) body.po_mode = options.poMode;
        if (options.rejectionRate !== undefined) body.rejection_rate = options.rejectionRate;

        const res = await fetch(`${sandboxBaseUrl()}/api/projects/sandbox/advance`, {
          method: 'POST',
          headers: sandboxHeaders(),
          body: JSON.stringify(body),
          signal: AbortSignal.timeout(15000),
        });

        if (!res.ok) {
          const err = await res.json().catch(() => ({ error: 'Unknown error' }));
          spinner.fail(`초기화 실패: ${err.error}`);
          return;
        }

        const result = await res.json();
        spinner.succeed(result.message || '초기화 완료');
        if (result.scenario_id) {
          console.log(`  시나리오: ${chalk.cyan(result.scenario_id)}`);
        }
      } catch (err) {
        spinner.fail(`초기화 실패: ${err instanceof Error ? err.message : err}`);
      }
    });
}
