/**
 * GFP Bot Callback API
 *
 * 봇(PlanClaw, GrowthClaw, DesignClaw 등)이 작업 결과를 GFP DB에 반영하는 엔드포인트.
 * 세 가지 콜백 타입:
 *   1. section-regeneration: 거절된 섹션의 재생성 결과 반영
 *   2. research-result: 리서치 작업 결과 반영
 *   3. stitch-export: Stitch 디자인 export 결과 반영
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  updateSectionContent,
  updateResearchTask,
  upsertSection,
  createStitchMaterial,
  listSections,
  getProject,
  updateSectionSlackThread,
} from '@/lib/gfp';
import { sendGfpQASlack, resolveGfpSlackContext } from '@/lib/slack';

export const dynamic = 'force-dynamic';

interface SectionRegenerationPayload {
  type: 'section-regeneration';
  section_id: string;
  content: string;
  bot_id: string;
}

interface ResearchResultPayload {
  type: 'research-result';
  task_id: string;
  result: string;
  bot_id: string;
}

interface StitchExportPayload {
  type: 'stitch-export';
  gfp_id: string;
  prompt_section_id: string;
  export_content: string;
  bot_id: string;
}

interface ClarificationReadyPayload {
  type: 'clarification-ready';
  gfp_id: string;
  bot_id: string;
}

type CallbackPayload =
  | SectionRegenerationPayload
  | ResearchResultPayload
  | StitchExportPayload
  | ClarificationReadyPayload;

export async function POST(request: NextRequest) {
  try {
    const body: CallbackPayload = await request.json();

    if (!body.type || !body.bot_id) {
      return NextResponse.json(
        { error: 'type and bot_id are required' },
        { status: 400 }
      );
    }

    switch (body.type) {
      case 'section-regeneration': {
        if (!body.section_id || !body.content) {
          return NextResponse.json(
            { error: 'section_id and content are required for section-regeneration' },
            { status: 400 }
          );
        }
        const section = await updateSectionContent(
          body.section_id,
          body.content,
          'pending-review'
        );
        if (!section) {
          return NextResponse.json({ error: 'Section not found' }, { status: 404 });
        }
        console.log(`[GFP Callback] Section ${body.section_id} regenerated by ${body.bot_id}`);
        return NextResponse.json({ ok: true, section });
      }

      case 'research-result': {
        if (!body.task_id || !body.result) {
          return NextResponse.json(
            { error: 'task_id and result are required for research-result' },
            { status: 400 }
          );
        }
        const task = await updateResearchTask(body.task_id, {
          status: 'completed',
          result: body.result,
        });
        if (!task) {
          return NextResponse.json({ error: 'Task not found' }, { status: 404 });
        }
        console.log(`[GFP Callback] Research ${body.task_id} completed by ${body.bot_id}`);
        return NextResponse.json({ ok: true, task });
      }

      case 'stitch-export': {
        if (!body.gfp_id || !body.prompt_section_id || !body.export_content) {
          return NextResponse.json(
            { error: 'gfp_id, prompt_section_id, and export_content are required for stitch-export' },
            { status: 400 }
          );
        }

        // 1. Stitch export를 gfp_materials에 저장
        const material = await createStitchMaterial({
          gfp_id: body.gfp_id,
          content: body.export_content,
        });

        // 2. Phase 3에 결과 섹션 생성 (프롬프트 섹션 키에서 번호 추출)
        const promptNum = body.prompt_section_id.match(/\d+/)?.[0] ?? '01';
        const resultSection = await upsertSection({
          gfp_id: body.gfp_id,
          phase: 3,
          section_key: `stitch-result-${promptNum}`,
          title: `Stitch Export #${promptNum} — Tailwind CSS`,
          content: body.export_content,
          source: 'designclaw',
          status: 'pending-review',
        });

        console.log(
          `[GFP Callback] Stitch export saved: material=${material.material_id}, section=${resultSection.section_id} by ${body.bot_id}`
        );
        return NextResponse.json({ ok: true, material, section: resultSection });
      }

      case 'clarification-ready': {
        if (!body.gfp_id) {
          return NextResponse.json(
            { error: 'gfp_id is required for clarification-ready' },
            { status: 400 }
          );
        }
        const project = await getProject(body.gfp_id);
        if (!project) {
          return NextResponse.json({ error: 'Project not found' }, { status: 404 });
        }

        // Find all Phase 3 sections with Q&A items
        const allSections = await listSections(body.gfp_id, 3);
        const qaSections = allSections.filter((s) => s.qa_items && Array.isArray(s.qa_items) && s.qa_items.length > 0);

        if (qaSections.length === 0) {
          return NextResponse.json({ ok: true, message: 'No Q&A sections found for Phase 3' });
        }

        // Send Q&A to Slack
        const slackCtx = await resolveGfpSlackContext(body.gfp_id);
        if (slackCtx.channelId) {
          const threadMap = await sendGfpQASlack({
            projectName: project.project_name,
            gfpId: body.gfp_id,
            sections: qaSections.map((s) => ({
              section_id: s.section_id,
              section_key: s.section_key,
              title: s.title,
              qa_items: (typeof s.qa_items === 'string' ? JSON.parse(s.qa_items) : s.qa_items) ?? [],
            })),
            channelId: slackCtx.channelId,
          });

          // Save thread_ts on each section
          for (const [sectionId, threadTs] of threadMap.entries()) {
            await updateSectionSlackThread(sectionId, threadTs);
          }
        }

        console.log(
          `[GFP Callback] Clarification ready: ${qaSections.length} Q&A sections for ${project.project_name} by ${body.bot_id}`
        );
        return NextResponse.json({ ok: true, qa_sections: qaSections.length });
      }

      default:
        return NextResponse.json(
          { error: `Unknown callback type: ${(body as CallbackPayload).type}` },
          { status: 400 }
        );
    }
  } catch (error) {
    console.error('GFP callback error:', error);
    return NextResponse.json({ error: 'Callback processing failed' }, { status: 500 });
  }
}
