-- 031_kb_manager_domain_register.sql
-- kb-manager 스킬에 도메인 등록 프로토콜 추가
-- CLI에 semo kb ontology --action register 명령어 추가에 맞춰 스킬 prompt 갱신
--
-- 변경 내용:
--   1. skill_definitions의 kb-manager prompt 업데이트 (도메인 등록 섹션 추가)

UPDATE semo.skill_definitions
SET prompt = E'---\nname: kb-manager\ndescription: SEMO KB 조회/검색/수정. semo CLI를 통해 팀 Knowledge Base에 접근.\n---\n\n# KB Manager\n\n## 환경 설정\n```bash\nsource ~/.semo.env\n```\n\n## 명령어\n\n| 작업 | 명령어 |\n|------|--------|\n| 검색 | `semo kb search \"검색어\" --domain <domain>` |\n| 정확 조회 | `semo kb get <domain> <key> [sub_key]` |\n| 목록 | `semo kb list --domain <domain>` |\n| 쓰기 | `semo kb upsert <domain> <key> [sub_key] --content \"내용\"` |\n| 온톨로지 | `semo kb ontology --action <action>` |\n| 도메인 등록 | `semo kb ontology --action register --domain <name> --type <type>` |\n\n## 예시\n```bash\n# 팀원 조회\nsemo kb get <org> team alice\n\n# 서비스 PO 조회\nsemo kb get my-service po\n\n# 검색\nsemo kb search \"PO\" --service my-service\n\n# 의사결정 기록\nsemo kb upsert <org> decision 2026-03-24/example --content \"의사결정 내용\"\n\n# 라우팅 테이블 (저장 위치 판단용)\nsemo kb ontology --action routing-table\n\n# 타입 스키마 조회\nsemo kb ontology --action schema --type service\n\n# 서비스 인스턴스 목록\nsemo kb ontology --action instances\n```\n\n## 조회 프로토콜 (읽기)\n\n정확한 domain/key 경로를 모를 때:\n1. `semo kb search \"검색어\"` — 결과에서 `[domain] key/sub_key` 확인\n2. 결과의 full key 경로로 `semo kb get <domain> <key> <sub_key>` 실행\n\n도메인 자체를 모를 때:\n- `semo kb ontology --action instances` — 서비스 도메인 목록\n- `semo kb ontology --action routing-table` — 전체 domain→key 매핑\n\n## 저장 프로토콜 (쓰기)\n\n1. `semo kb ontology --action routing-table` — 저장 위치 확인\n2. `semo kb upsert <domain> <key> [sub_key] --content \"내용\"`\n\n## 도메인 등록 프로토콜\n\n새 도메인(서비스, 팀원, 봇 등)이 필요할 때:\n\n### Step 1: 타입 확인\n```bash\nsemo kb ontology --action types\n```\n사용 가능한 타입: service, team, person, bot, organization, decision, process 등\n\n### Step 2: 타입 스키마 확인 (필수 키 파악)\n```bash\nsemo kb ontology --action schema --type <type>\n```\n`*` 표시가 required 키 — 등록 시 자동으로 placeholder entry 생성됨\n\n### Step 3: 도메인 등록\n```bash\n# 기본 (필수 KB entry 자동 생성)\nsemo kb ontology --action register --domain <name> --type <type> --description \"설명\"\n\n# 서비스 그룹 지정\nsemo kb ontology --action register --domain <name> --type <type> --service <service> --description \"설명\"\n\n# 또는 onto 서브커맨드\nsemo onto register <name> --type <type> --description \"설명\"\n```\n\n### Step 4: 필수 데이터 입력\n등록 후 placeholder로 생성된 필수 키에 실제 데이터 입력:\n```bash\nsemo kb upsert <domain> <key> --content \"실제 내용\"\n```\n\n### 예시: 팀원 도메인 등록\n```bash\n# 1. team 타입 스키마 확인\nsemo kb ontology --action schema --type team\n\n# 2. 도메인 등록\nsemo kb ontology --action register --domain alice --type team --description \"Alice — 팀원\"\n\n# 3. 필수 데이터 입력\nsemo kb upsert alice profile --content \"역할: 프론트엔드 개발자\"\n```\n\n## 규칙\n- psql 직접 쿼리 금지 — 반드시 이 명령어 사용 (임베딩 자동 생성, 스키마 검증)\n- search 결과의 key/sub_key 경로를 그대로 get에 사용할 것\n- 도메인/키를 추측하지 말고 ontology 또는 search로 확인\n- 새 도메인 필요 시 반드시 ontology register로 등록 (직접 DB INSERT 금지)\n',
    version = '3.0',
    updated_at = NOW()
WHERE name = 'kb-manager' AND office_id IS NULL;
