-- 047: gfp-manager 스킬 → service-project-manager 리프레이밍
--
-- GFP는 이제 "프로젝트 관리 시스템"이 아니라 "신규 서비스를 띄우는 파이프라인".
-- service_* 테이블이 모든 서비스의 SoT.
-- 스킬 프롬프트를 이 맥락으로 업데이트.
--
-- 선행 조건: 045_service_table_rename_and_projection.sql 적용 완료

UPDATE semo.skill_definitions
SET
  display_name = 'Service Project Manager',
  description  = '서비스 프로젝트 관리 — service_* 테이블 CRUD. GFP(신규 서비스 파이프라인) + 기존 서비스 운영 공통.',
  prompt = E'---\nname: service-project-manager\ndescription: 서비스 프로젝트 관리 — service_* 테이블 CRUD, 섹션 생성/수정, 리서치 결과 반영.\n---\n\n# Service Project Manager\n\nservice_* 테이블(구 gfp_*)의 프로젝트/섹션/리서치 관리 스킬.\n봇(PlanClaw, DesignClaw, GrowthClaw, InfraClaw 등)이 대시보드 API를 통해 접근.\n\n## 핵심 개념\n\n- **service_projects**: 모든 서비스의 메타데이터 (lifecycle: build → ops → sunset)\n- **GFP Pipeline**: 신규 서비스를 service_projects에 등록하고 Phase 0~9를 진행하는 파이프라인\n- **Projection Key**: KB의 spec/*, pm-status 등은 파이프라인이 자동 동기화 — 봇이 직접 쓰면 CLI가 거부\n\n## API Endpoints\n\nBase URL: `${SEMO_DASHBOARD_URL}` (default: http://localhost:3000)\n\n### 프로젝트 조회\n```bash\n# 프로젝트 목록\ncurl -s ${SEMO_DASHBOARD_URL}/api/gfp | jq\n\n# 프로젝트 상세 (progress 포함)\ncurl -s ${SEMO_DASHBOARD_URL}/api/gfp/{gfp_id} | jq\n```\n\n### 섹션 조회/수정\n```bash\n# 섹션 목록 (페이즈별, 트랙별)\ncurl -s \"${SEMO_DASHBOARD_URL}/api/gfp/{gfp_id}/sections?phase=1&track=plan\" | jq\n\n# 섹션 생성/수정 (upsert)\ncurl -X POST ${SEMO_DASHBOARD_URL}/api/gfp/{gfp_id}/sections \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{ \"phase\": 1, \"section_key\": \"overview\", \"title\": \"Overview\", \"content\": \"...\", \"status\": \"pending-review\", \"source\": \"planclaw\" }''\n\n# 섹션 내용 업데이트\ncurl -X PATCH ${SEMO_DASHBOARD_URL}/api/gfp/{gfp_id}/sections \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{ \"section_id\": \"...\", \"action\": \"update-content\", \"content\": \"수정된 내용\", \"status\": \"pending-review\" }''\n```\n\n### 봇 콜백 (결과 반영)\n```bash\n# PlanClaw: 재생성 결과\ncurl -X POST ${SEMO_DASHBOARD_URL}/api/gfp/callback \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{ \"type\": \"section-regeneration\", \"section_id\": \"...\", \"content\": \"...\", \"bot_id\": \"planclaw\" }''\n\n# GrowthClaw: 리서치 결과\ncurl -X POST ${SEMO_DASHBOARD_URL}/api/gfp/callback \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{ \"type\": \"research-result\", \"task_id\": \"...\", \"result\": \"...\", \"bot_id\": \"growthclaw\" }''\n\n# DesignClaw: Stitch 디자인 결과\ncurl -X POST ${SEMO_DASHBOARD_URL}/api/gfp/callback \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{ \"type\": \"stitch-export\", \"gfp_id\": \"...\", \"content\": \"...\", \"bot_id\": \"designclaw\" }''\n```\n\n### 인프라 요청 (Track B)\n```bash\n# 인프라 요구사항 생성\ncurl -X POST ${SEMO_DASHBOARD_URL}/api/gfp/{gfp_id}/infra-requests \\\n  -H \"Content-Type: application/json\" \\\n  -d ''{ \"source_phase\": 2, \"category\": \"oauth\", \"title\": \"OAuth 설정 필요\" }''\n```\n\n## Data Routing 규칙\n\n| 데이터 | 쓰기 대상 | 금지 |\n|--------|-----------|------|\n| 섹션 콘텐츠 | PM API (이 스킬) | KB spec/* 직접 쓰기 ✗ |\n| 서비스 메타데이터 | KB (`semo kb upsert`) | PM 테이블 직접 수정 ✗ |\n| 진행 상태 | (자동) pm-pipeline | 봇이 pm-status 직접 쓰기 ✗ |\n\n## 규칙\n- 섹션 수정 시 status를 반드시 \"pending-review\"로 설정\n- source 필드로 출처 명시: planclaw / growthclaw / designclaw / infraclaw / imported / manual\n- 콜백 API 사용 시 bot_id 필수\n- **Projection Key 쓰기 금지**: spec/*, pm-status, gfp-status, infra-status는 파이프라인이 자동 관리\n',
  metadata = '{"bot_ids": ["planclaw", "growthclaw", "designclaw", "infraclaw"]}',
  version  = '2.0'
WHERE name = 'gfp-manager';
