-- 051: service-migration 스킬 프롬프트 강화
--
-- 문제: 봇이 KB 엔트리만 보고 "이미 등록됨"으로 판단 → 실제 service_projects 미등록 서비스를 놓침
-- 해결: CLI 실행 필수 지시 + KB ≠ 등록 경고 + 판단 기준 명확화

UPDATE semo.skill_definitions
SET prompt = E'---\nname: service-migration\ndescription: 기존 운영 서비스를 service_projects 테이블에 이식\n---\n\n# Service Migration\n\n기존 운영 서비스를 `service_projects` 테이블에 등록하는 스킬.\nGFP(신규 서비스 파이프라인)를 거치지 않은 서비스를 경량 온보딩.\n\n## ⚠️ 핵심 원칙 (NON-NEGOTIABLE)\n\n1. **\"등록됨\" = `service_projects` 테이블에 행이 있는 것**. KB 엔트리가 있다고 등록된 것이 아님.\n2. **판단 금지**: KB를 조회해서 자체적으로 등록 여부를 판단하지 마라.\n3. **반드시 CLI 실행**: 아래 CLI 명령을 직접 실행하고, 그 결과로 응답하라.\n\n## 트리거\n- \"기존 서비스 등록해줘 {domain}\"\n- \"미등록 서비스 전체 등록해줘\"\n- \"서비스 목록 보여줘\"\n\n## 실행 방법 (반드시 CLI 실행)\n\n### 단일 서비스 이식\n```bash\nsemo service migrate --domain {domain}\n```\nCLI가 내부적으로: service_projects 중복 체크 → KB audit → INSERT → pm-summary 생성\n\n### 미등록 전체 일괄 이식\n```bash\nsemo service migrate --all\n```\n\n### 미리보기 (DB 변경 없음)\n```bash\nsemo service migrate --all --dry-run\n```\n\n### 서비스 목록 (등록/미등록 확인)\n```bash\nsemo service list\n```\n\n## 올바른 워크플로우\n1. 사용자가 \"기존 서비스 등록해줘 {domain}\" 요청\n2. `semo service migrate --domain {domain}` CLI 실행\n3. CLI 출력 결과를 그대로 사용자에게 전달\n4. 이미 등록된 경우 CLI가 \"이미 등록됨\" 메시지를 출력함 — 이것만 신뢰\n\n## ❌ 잘못된 워크플로우\n1. 사용자가 \"기존 서비스 등록해줘 {domain}\" 요청\n2. `semo kb get {domain} base-information` 등 KB 조회\n3. KB 엔트리가 있으니 \"이미 등록됨\"이라고 판단 ← **이것이 버그**\n\n## 이식 흐름 (CLI 내부 동작)\n1. service_projects 테이블에서 중복 체크\n2. KB에서 base-information, po, status, tech-stack 등 자동 수집\n3. KB status → lifecycle+status 매핑 (active→ops, hold→paused, deprecated→sunset)\n4. service_projects INSERT (lifecycle=''ops'')\n5. pm-summary projection key 자동 생성\n6. 감사(audit) 리포트 출력\n\n## 감사 리포트 해석\n- **mapped**: service_projects 컬럼에 매핑된 KB 엔트리\n- **metadata**: JSONB에 저장된 추가 정보 (repo, slack-channel 등)\n- **kb-only**: KB에만 존재하는 정상 엔트리 (kpi, milestone 등)\n- **warnings**: 비표준 키 → kb_type_schema 등록 제안\n- **missingRequired**: 필수 키 누락 → 사용자에게 보완 요청\n\n## Data Routing\n- service_projects 테이블 = 실행 상태 SoT\n- KB = 서비스 참조 지식 SoT\n- projection key (spec/*, pm-status 등)는 파이프라인만 쓰기 가능\n',
    version = '1.1'
WHERE name = 'service-migration';
